### PR TITLE
sandstorm-http-bridge: re-save identity caps if they fail to restore

### LINKED ISSUE #2440: identities saved through sandstorm-http-bridge break after backup/restore
1. Alice creates a new rocket.chat grain G.
  2. Alice shares G to Bob.
  3. Both Alice and Bob confirm their usernames in G.
  4. Alice downloads a backup of G and then restores it as H.
  5. Alice shares H with Bob.
  6. Bob visits H, then closes H.
  7. H reboots (perhaps through Alice clicking the "restart" button in the topbar).
  8. Alice writes a message in H's "#general" channel, @-mentioning Bob.

I expect Bob to receive a notification about the @-mention, but he does not!
The problem is that H's sturdyref for Bob's identity is only valid within G, and H never tries to refresh the sturdyref, even if calling `restore()` on it fails.

### PR DESCRIPTION
**Pull request by dwrensha**
Fixes #2440.

Adds some logic so that now, every time that we add a new entry to `identitiesMap`, if there is already a corresponding sturdyref on disk, we kick off a task that tries to restore that sturdyref, and we re-save it upon failure.

### CODE REVIEW

File: src/sandstorm/sandstorm-http-bridge.c++ [hunk 1]
```diff
@@ -1195,7 +1201,59 @@ private:
     auto req = apiCap.restoreRequest();
     req.setToken(percentDecode(buf));
 
-    return req.send().getCap().castAs<Identity>();
+    // Don't directly call `getCap()` on the `RemotePromise` because we want to make sure
```
Comment (kentonv) [inline src/sandstorm/sandstorm-http-bridge.c++]: This breaks pipelining in several cases, but it looks like there's only one call site that actually cares about catching exceptions. Can you instead go back to returning a pipelined capability, but call `.whenResolved()` on it in the case where you're actually testing the capability's validity? This should be equivalent.

File: src/sandstorm/sandstorm-http-bridge.c++ [hunk 2]
```diff
@@ -1195,7 +1201,59 @@ private:
...
+      // We name the trash file after the token, not the identity ID. This way, it's okay
+      // if we overwrite an existing entry of the trash directory.
+      auto trashSymlink = kj::heapString(buf);
+      KJ_SYSCALL(renameat(identitiesDir, symlink.cStr(), trashDir, trashSymlink.cStr()));
+
+      auto req = apiCap.dropRequest();
+      req.setToken(percentDecode(buf));
+      tasks.add(req.send().then([KJ_MVCAP(trashSymlink), this](auto response) -> void {
+        KJ_SYSCALL(unlinkat(trashDir, trashSymlink.cStr(), 0));
+        KJ_SYSCALL(fsync(trashDir));
```
Comment (kentonv) [inline src/sandstorm/sandstorm-http-bridge.c++]: I think this fsync() isn't accomplishing anything except to slow things down, since nothing is actually gated on the completion of this operation. Normally you need to fsync() before returning a success code to the caller, so that the caller knows that success means durability, but there's no caller here.

With or without the fsync(), it's possible to be left in a state where there are tokens in the trash that were in fact already dropped. That's fine, since the worst case is that drop() will be harmlessly called again later.

File: src/sandstorm/sandstorm-http-bridge.c++ [hunk 3]
```diff
@@ -1195,7 +1201,59 @@ private:
...
+  void saveIdentityInternal(kj::StringPtr textId, Identity::Client identity) {
+    auto req = apiCap.saveRequest();
+    req.setCap(identity);
+    req.initLabel().setDefaultText("user identity");
+    tasks.add(req.send().then([this,textId](auto result) -> void {
+      // Sandstorm tokens are primarily text but use percent-encoding to be safe.
+      auto tokenText = percentEncode(result.getToken());
+
+      // Clean up any existing symlink.
+      dropIdentity(textId);
```
Comment (kentonv) [inline src/sandstorm/sandstorm-http-bridge.c++]: Hmm, it seems there's a period of time here between dropIdentity() and symlinkat() during which a crash would lose the identity altogether.

However, presumably if we're saving over an existing token, it's because the existing token was already observed to be dead?

Maybe dropIdentity() should actually be called at the point where this observation was made, rather than here? And if, in the meantime, some other concurrent task has saved a copy of the identity, then we should not overwrite it?

File: src/sandstorm/sandstorm-http-bridge.c++ [hunk 4]
```diff
@@ -1072,25 +1073,20 @@ public:
...
-          // allocating a block.
-          KJ_SYSCALL(symlinkat(tokenText.cStr(), identitiesDir, textIdRef.cStr()));
-
-          // Make sure it's really saved.
-          KJ_SYSCALL(fsync(identitiesDir));
+        saveIdentityInternal(textIdRef, kj::mv(identity));
+      } else {
+        // Try restoring the existing SturdyRef and re-save on failure.
+        tasks.add(loadIdentityFromDisk(textIdRef).ignoreResult().catch_(
+            [this, textIdRef, identity](auto error) mutable {
```
Comment (kentonv) [inline src/sandstorm/sandstorm-http-bridge.c++]: KJ_MVCAP(identity)? (saves a refcount)

File: src/sandstorm/sandstorm-http-bridge.c++ (hunk 1 above)
Comment (dwrensha) [inline src/sandstorm/sandstorm-http-bridge.c++]: Ah, I hadn't realized that I could both pipeline and detect errors like that. Updated.

File: src/sandstorm/sandstorm-http-bridge.c++ (hunk 2 above)
Comment (dwrensha) [inline src/sandstorm/sandstorm-http-bridge.c++]: Removed.

File: src/sandstorm/sandstorm-http-bridge.c++ (hunk 3 above)
Comment (dwrensha) [inline src/sandstorm/sandstorm-http-bridge.c++]: Ah, I need to deal with the double-save case too. Doing it...

File: src/sandstorm/sandstorm-http-bridge.c++ (hunk 4 above)
Comment (dwrensha) [inline src/sandstorm/sandstorm-http-bridge.c++]: Done.

File: src/sandstorm/sandstorm-http-bridge.c++ [hunk 5]
```diff
@@ -1129,14 +1130,15 @@ public:
                                       -> kj::Promise<Identity::Client> {
         if (e2.getType() == kj::Exception::Type::DISCONNECTED) {
           // Disconnected. We'll need to reload from disk.
-          Identity::Client newIdentity = loadIdentityFromDisk(textId);
-
-          // Save the new identity to the map so that we don't have to reload it again.
-          auto iter = liveIdentities.find(textId);
-          KJ_ASSERT(iter != liveIdentities.end());
-          iter->second.identity = newIdentity;
+          auto identity = loadIdentityFromDisk(textId);
```
Comment (kentonv) [inline src/sandstorm/sandstorm-http-bridge.c++]: By renaming this `newIdentity` -> `identity`, you're now shadowing a captured variable, which is confusing.

Comment (dwrensha) [inline src/sandstorm/sandstorm-http-bridge.c++]: OK. Unrenamed.

File: src/sandstorm/sandstorm-http-bridge.c++ (hunk 3 above)
Comment (dwrensha) [inline src/sandstorm/sandstorm-http-bridge.c++]: > However, presumably if we're saving over an existing token, it's because the existing token was already observed to be dead?

Yeah, but there's also a nonzero chance that the failure was somehow transient, so we'd like to delay dropping the old sturdyref as long as we can.

We want to:
  1. Avoid leaking sturdyrefs.
  2. Not delete anything in the identities/ directory until we have something to replace it with. Ideally, the replacement would be atomic.
  3. Keep it simple.

> Maybe dropIdentity() should actually be called at the point where this observation was made, rather than here? And if, in the meantime, some other concurrent task has saved a copy of the identity, then we should not overwrite it?

This seems strictly worse for goals (2) and (3).
