### PR TITLE
Fail early if we can't access var/sandstorm

### LINKED ISSUE #711: Running sandstorm admin-token as non-privileged user crashes
Should probably offer a user-readable error "Run as root user or under sudo"

```
$ sandstorm admin-token
*** Uncaught exception ***
sandstorm/util.c++:47: failed: open(name.cStr(), flags, mode): Permission denied; name = ../var/sandstorm/adminToken
stack: 0x541e08 0x541d89 0x541d7a 0x5143a1 0x515025
```

### PR DESCRIPTION
**Pull request by mrdomino**
Fixes #711 via the `access()` method.

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

File: src/sandstorm/run-bundle.c++ [hunk 1]
```diff
@@ -647,13 +647,13 @@ public:
     // Make sure the pidfile is close-on-exec.
     KJ_SYSCALL(fcntl(pidfile, F_SETFD, FD_CLOEXEC));
 
-    changeToInstallDir();
+    changeToInstallDirAndCheckAccess();
```
Comment (kentonv) [inline src/sandstorm/run-bundle.c++]: I'm somewhat terrified that there could be some significant number of installations out there that randomly don't have /var/sandstorm writable by the group, but have the appropriate subdirectories writable such that things do actually still work. If we add a check in `continue_` then all those servers will die when they update. Similarly if the check is in `start` then they'll all die on their next reboot. I really don't want people to start fearing that an auto-update might randomly kill their server, so I'd rather not perform the check in these cases.

File: src/sandstorm/run-bundle.c++ [hunk 2]
```diff
@@ -742,7 +742,7 @@ public:
   }
 
   kj::MainBuilder::Validity status() {
-    changeToInstallDir();
+    changeToInstallDirAndCheckAccess();
```
Comment (kentonv) [inline src/sandstorm/run-bundle.c++]: Arguably `status` shouldn't require this check. It can often complete just fine without any write permissions.

File: src/sandstorm/run-bundle.c++ [hunk 3]
```diff
@@ -921,8 +921,15 @@ private:
     return kj::heapString(exeName.slice(0, KJ_ASSERT_NONNULL(exeName.findLast('/'))));
   }
 
-  void changeToInstallDir() {
+  void changeToInstallDirAndCheckAccess() {
     KJ_SYSCALL(chdir(getInstallDir().cStr()));
+    if (access("../var/sandstorm", W_OK) == -1) {
+      if (errno == EACCES) {
+        KJ_FAIL_REQUIRE("Sandstorm must be run as root or a member of SERVER_USER's group.");
```
Comment (kentonv) [inline src/sandstorm/run-bundle.c++]: This error is not quite correct:
- If Sandstorm was installed as root, then it must be started as root, regardless of SERVER_USER.
- If Sandstorm was installed as non-root, then it must always be run as the same user who installed it, and I think SERVER_USER is not actually specified in the config.

Comment (kentonv) [inline src/sandstorm/run-bundle.c++]: However, `dev` should never run as root, even if Sandstorm was installed as root; it should be run by someone inside the server user's group.

**Comment by kentonv** [comment]
Hmm, this seems to be more complicated than it seemed. Possibly we should focus solely on doing the check in the `admin-token` command for now, since that was what issue #711 complained about?

**Comment by mrdomino** [comment]
Sounds reasonable. I'll resubmit next time I get a chance to work on it.

File: src/sandstorm/run-bundle.c++ (hunk 3 above)
Comment (mrdomino) [inline src/sandstorm/run-bundle.c++]: Okay, so special message for the dev command? Is there an easily-detectable way of finding out whether Sandstorm was installed as root? Or should the message just include the full conditional?

**Comment by mrdomino** [comment]
Resubmitted. Sorry it took so long -- unusually busy these days.

**Comment by kentonv** [comment]
Thanks! To answer this question:

> Okay, so special message for the dev command? Is there an easily-detectable way of finding out whether Sandstorm was installed as root? Or should the message just include the full conditional?

There's a `runningAsRoot` member which tells you if the command is running as root. If `readConfig()` has been called, it will have verified if `runningAsRoot` is true then `SERVER_USER` is configured. Arguably if `runningAsRoot` is not true then `readConfig()` should fail if `SERVER_USER` *is* configured, since the presence of `SERVER_USER` implies that Sandstorm should start as root (and should setuid() itself later).

Anyway, not important.
