### PR TITLE
run-bundle: fix up sandcats permissions

### LINKED ISSUE #372: run-bundle should sanity-check sandcats key permissions
Per #368, some installs may have the wrong permissions for Sandcats keys.

This issue tracks doing the work of adjusting `run-bundle` to do similar chown-ing, to fix installs in place.

### PR DESCRIPTION
**Pull request by zarvox**
Fixes #372.

### CODE REVIEW

**Comment by garply** [comment]
Hey admins! Can one of you let me know if it's safe to build this pull request? See https://alpha.sandstorm.io/grain/kB7bofATTL2jGuKSFwmqdA/GithubPRCommands for a list of commands.

**Comment by paulproteus** [comment]
Garply, add to whitelist

**Comment by paulproteus** [comment]
Garply, it's nice that I'm an admin

File: src/sandstorm/run-bundle.c++ [hunk 1]
```diff
@@ -2147,6 +2149,33 @@ private:
...
+  void fixSandcatsPermissions(const Config& config) {
+    // An older version of the sandcats installer left various sandcats-related files around owned
+    // by root, rather than the sandstorm server user.
+    // var/sandcats should be 0700, with corrected owner/group
+    if (access("../var/sandcats", F_OK) == 0) {
+        setOwnerGroupAndMode(kj::str("../var/sandcats"), 0700, config.uids.uid, config.uids.gid);
+    }
+    // var/sandcats/{register-log,id_rsa{,.pub,private_combined}} should each be 0640, with corrected
+    // owner/group
+    kj::Vector<const char*> files;
```
Comment (kentonv) [inline src/sandstorm/run-bundle.c++]: How about:

    kj::StringPtr files[] = { "register-log", ... };

or:

    static const char* const files[] = { "register-log", ... };

The for() loop should work correctly with either of these without changes, though I'd maybe change the `auto& f` to just `auto f` since these are trivially-copyable types.

Comment (zarvox) [inline src/sandstorm/run-bundle.c++]: Amended as suggested.

**Comment by kentonv** [comment]
Looks good, merged!

BTW, not a big deal in this case, but I generally like to have comments addressed in a separate commit rather than squashed so that I can easily see exactly what changed. I went and wrote up this and some of our other previously-unwritten rules here:

https://github.com/sandstorm-io/sandstorm/wiki/Pull-Request---Code-Review-Procedure

**Comment by paulproteus** [comment]
I just saw this new wiki page. Massive +1.​
