### PR TITLE
Correctly serve utf8 filenames for backups

### LINKED ISSUE #2597: Download backup of grain with non-ascii-clean title can fail
To reproduce:

* Open https://oasis.sandstorm.io
* Create a new Wekan grain
* rename the grain "šos"
* click the download arrow to attempt to download a backup

Expected behavior: browser downloads a file named šos.zip

Actual behavior: browser says something like "/tmp/mozilla_zarvox0/tuPw8fkf.zip.part could not be saved, because the source file could not be read", and you get no backup.

----
This seems to not affect all apps equally.  Attempting the same with Etherpad successfully downloads an appropriately-named zip with correct content.

It's not immediately clear to me if this is a bug in the frontend, the backend, their interactions, or some combination thereof.

### PR DESCRIPTION
**Pull request by jparyani**
This follows RFC 6266, which all browsers have supported for a while now.

Fixes #2597

### CODE REVIEW

File: shell/server/backup.js [hunk 1]
```diff
@@ -183,7 +183,7 @@ Router.map(function () {
       }
 
       let started = false;
-      const filename = (token.name.replace(/["\n]/g, "") || "backup") + ".zip";
+      const filename = encodeURIComponent(token.name || "backup") + ".zip";
```
Comment (kpreid) [inline shell/server/backup.js]: Might I suggest naming the variable "encodedFilename" or similar, so the uses of it below look less suspicious?
