### PR TITLE
Route/proxy non-main-host requests before sockjs's handler swallows them

### LINKED ISSUE #1186: Grains fail to load when SockJS falls back to long polling
Meteor apps use SockJS which falls back to long polling when websocket connections fail.

However when running in Sandstorm on a server without websocket support (or being proxied through a webserver without support) grains get stuck in a reload loop.

But Sandstorm Shell does work, successfully falling back to long polling.

This is quite easily reproducible by setting up nginx as a reverse_proxy to Sandstorm using the config here: https://github.com/iflowfor8hours/sandcastle/blob/master/templates/reverse_proxy.conf.j2 but ripping out the websocket configuration.

I've attached tcpdump captures from the shell and wekan without websocket forwarding configured that I was looking at to attempt to debug this.

[shell.txt](https://github.com/sandstorm-io/sandstorm/files/40717/shell.txt)
[wekan.txt](https://github.com/sandstorm-io/sandstorm/files/40718/wekan.txt)

### PR DESCRIPTION
**Pull request by zarvox**
This fixes the longstanding "Meteor app refresh loop" issue.

Meteor's sockjs inserts itself as the first request listener on the Meteor HTTP
handler object.  Normally, this is fine, and keeps DDP requests from
accidentally getting routed to the application handlers.  This is problematic
for programs that happen to implement a proxy, and which need to proxy requests
that use the same paths and overall protocol as Meteor does internally.

As a result of the sockjs middleware being first in the chain, XHRs to an
Meteor app's sockjs endpoint would wind up getting answered by Sandstorm's
instance of sockjs and communicating over DDP to Sandstorm itself.  So any app
that fell back to long-polling would speak DDP to Sandstorm, rather than to the
intended app's backend.

Meteor hashes all the code that goes into an app to determine if a reload is
needed to have the latest code running on the client.  It publishes the current
version of the client code in a collection over DDP.  This lead the code
running in the browser to believe that there had been a code change, since it
was now getting the hash for **Sandstorm's** shell code over DDP, which did not
match the hash for the app's code.  So the app would refresh the page, hoping
to load the new code.  Browsers would cache that websockets had failed for that
host, and so the app would load the code, learn about Sandstorm's code version
over sockjs long-polling DDP, and attempt to refresh again.

The solution here is to do Sandstorm's proxying earlier in the request dispatch
chain.  We splice our own handler in after ddp-server has installed its sockjs
handler, and now everything works as intended.

Fixes #1186.

### CODE REVIEW

File: shell/server/pre-meteor.js [hunk 1]
```diff
@@ -341,180 +341,206 @@ function serveStaticAsset(req, res) {
...
+
+  nonMeteorRequestHandler.use(serveMeteorOrStaticPublishing);
+
+  WebApp.httpServer.removeAllListeners("request");
+  WebApp.httpServer.on("request", (req, res) => {
     if (!req.headers.host) {
-      res.writeHead(400, { 'Content-Type': 'text/plain' });
-      res.end('Missing Host header');
-      return;
+      throw new Meteor.Error(400, 'Missing Host header');
```
Comment (dwrensha) [inline shell/server/pre-meteor.js]: There is no exception handler to catch this error, so the frontend dies when it is triggered! I think you should instead do something like:

```javascript
      res.writeHead(400, { 'Content-Type': 'text/plain' });
      res.end('Missing Host header');
      return;
```

Note that you can test what happens with an empty Host header by doing the following, assuming you are not in `run-dev.sh` mode and your server is not behind a reverse proxy:
```
curl -v -H 'Host:' http://sandstorm.example.com/
```

File: shell/server/pre-meteor.js [hunk 2]
```diff
@@ -341,180 +341,206 @@ function serveStaticAsset(req, res) {
...
+  targetUrl.host = hostname + ':' + targetUrl.port;
+
+  // The following allows to avoid decoding + re-encoding query
+  // string parameters, if provided.
+  targetUrl = Url.resolve(Url.format(targetUrl), url);
+  return targetUrl;
+};
+
+const dispatchToMeteorOrStaticPublishing = (req, res, next, redirectRatherThanServeShell) => {
+  if (!req.headers.host) {
```
Comment (dwrensha) [inline shell/server/pre-meteor.js]: The new `req.headers.host` check in the "request" handler makes this check redundant. Is there a good reason to keep this around?

Comment (zarvox) [inline shell/server/pre-meteor.js]: It is still needed for the `redirectToMeteorOrServeStaticPublishing` codepath (though perhaps that suggests that the check should be moved out to there).

File: shell/server/pre-meteor.js (hunk 1 above)
Comment (zarvox) [inline shell/server/pre-meteor.js]: Yikes.

Yeah, I should double-check what code is responsible for catching exceptions/failed promises further down too.

Comment (zarvox) [inline shell/server/pre-meteor.js]: It looks like the rest of the Sandstorm-proxy request handlers properly catch anything they throw, and Meteor of course catches anything that is dispatched through its handlers.

The upgrade handler itself uses a Promise and simply destroys the socket if any exception is raised.

**Comment by zarvox** [comment]
Garply, retest this please

**Comment by zarvox** [comment]
Previous failure was caused by the fix from sandstorm-io/capnproto#344 causing the randomized schema-evolution test to fail.  It's good that the capnproto tests catch that particular evolution issue, but we can safely ignore it here.

File: shell/server/pre-meteor.js [hunk 3]
```diff
@@ -341,180 +341,208 @@ function serveStaticAsset(req, res) {
...
 
-  const dispatchToMeteorOrStaticPublishing = (req, res, next, redirectRatherThanServeShell) => {
+  // Construct the middleware chain for requests to non-DDP, non-shell hosts.
+  const nonMeteorRequestHandler = Connect();
+  // BlackrockPayments is only defined in the Blackrock build of Sandstorm.
+  if (global.BlackrockPayments) { // Have to check with global, because it could be undefined.
+    nonMeteorRequestHandler.use(BlackrockPayments.makeConnectHandler(globalDb));
+  }
+
+  nonMeteorRequestHandler.use(serveMeteorOrStaticPublishing);
```
Comment (dwrensha) [inline shell/server/pre-meteor.js]: The names `nonMeteorRequestHandler` and `serveMeteorOrStaticPublishing` are confusing when taken together like this. Are we considering requests to grains to be `Meteor` or `nonMeteor`?

File: shell/server/pre-meteor.js [hunk 4]
```diff
@@ -341,180 +341,208 @@ function serveStaticAsset(req, res) {
...
+
+  WebApp.httpServer.removeAllListeners("request");
+  WebApp.httpServer.on("request", (req, res) => {
```
Comment (dwrensha) [inline shell/server/pre-meteor.js]: I'm still a bit nervous about the fact that this stretch of code does not have an exception handler. Sure, maybe we can verify by inspection now that nothing bad is likely to happen, but who knows how the code will evolve? Especially because this code gets hit on *every* request, it seems like going out of our way for robustness would be worthwhile.

File: shell/server/pre-meteor.js (hunk 3 above)
Comment (zarvox) [inline shell/server/pre-meteor.js]: Good point, the names of these functions and their parameters became quite confusing.

I've reworked the dispatch order and the naming, so hopefully it's clearer now.

File: shell/server/pre-meteor.js (hunk 4 above)
Comment (zarvox) [inline shell/server/pre-meteor.js]: I'm pretty sure all the other things that can fail already catch their exceptions, but I suppose the real point of exceptions is to guard against programmer error, so I can't really argue with that. :)

Added top-level try/catch blocks here and for `handleNonMainPortRequest`.

File: shell/server/pre-meteor.js [hunk 5]
```diff
@@ -422,45 +415,29 @@ const dispatchToMeteorOrStaticPublishing = (req, res, next, redirectRatherThanSe
...
 // port.
-const serveMeteorOrStaticPublishing = (req, res, next) => {
-  return dispatchToMeteorOrStaticPublishing(req, res, next, false);
+const handleNonMeteorRequestDirectly = (req, res, next) => {
+  return handleNonMeteorRequest(req, res, next, false);
 };
 
 // "Alternate ports" are ports other than the main HTTP or HTTPS
-// port. For requests to the shell & grains, we redirect to the main
+// port. For requests to the shell, grains, we redirect to the main
```
Comment (dwrensha) [inline shell/server/pre-meteor.js]: Weird punctuation edit here.

**Comment by dwrensha** [comment]
Looks good to me.

File: shell/server/pre-meteor.js (hunk 5 above)
Comment (zarvox) [inline shell/server/pre-meteor.js]: Rewrote that whole comment to make clearer/more accurate.

**Comment by zarvox** [comment]
I think the test failure is the IpInterface test being racy.  It passed in the previous commit, and the only difference is comments.

**Comment by zarvox** [comment]
Garply, retest this please
