### PR TITLE
Get offer templates working for anonymous users.

### LINKED ISSUE #555: Offer templates do not work for anonymous users.
The `renderTemplate` handler calls the `newApiToken()` Meteor method, which throws an exception if there is no current user. It used to be that throwing an exception was the only reasonable option here, because we did not have a good way to create a token with appropriately attenuated permissions. Now that we have the notions of parent tokens and child tokens, we have a potentially more natural way to handle this case. Once #516 lands, we should be able to revise `newApiToken()` such that it can create a child token when an anonymous user requests a token.

### PR DESCRIPTION
**Pull request by dwrensha**
This fixes #555.

### CODE REVIEW

File: shell/server/hack-session.js [hunk 1]
```diff
@@ -323,10 +323,26 @@ HackSessionContextImpl.prototype.generateApiToken = function (petname, userInfo,
...
+    var parentToken;
+    if (!userId) {
+      if (!rawParentToken) {
+        throw new Meteor.Error(403, "If you are not logged in, you must specify a parent token to " +
+                                    "create a new API token.");
+      } else {
+        check(rawParentToken, String);
+        parentToken = Crypto.createHash("sha256").update(rawParentToken).digest("base64");
+        var parentApiToken = ApiTokens.findOne({_id: parentToken, grainId: grainId,
+                                                objectId: {$exists: false}});
```
Comment (jparyani) [inline shell/server/hack-session.js]: I think you forgot about `frontendRef` in addition to `objectId`. I do kind of wish there was a field that identifies a token as a UiView...

Comment (dwrensha) [inline shell/server/hack-session.js]: If `frontendRef` is set then `grainId` is not set, so I think we're covered.

Comment (jparyani) [inline shell/server/hack-session.js]: Yep, you're right, we should be good.

**Comment by dwrensha** [comment]
I've pushed a new commit to this branch, adding some significant changes.

The main improvement is that offer template tokens get kept alive as long as their corresponding templates are open.

Another change is that the fifth argument to `newApiToken()` is now a duration rather than an absolute time. I think this is better for situations when the user's browser might be out of sync.

**Comment by dwrensha** [comment]
Oops, I just realized that the expiration stuff doesn't quite make sense in what I just pushed. Please stand by...

**Comment by dwrensha** [comment]
OK, this should work now.

File: shell/shared/grain.js [hunk 2]
```diff
@@ -590,9 +590,14 @@ if (Meteor.isClient) {
           assignment = call.roleAssignment;
         }
         // Tokens expire by default in 5 minutes from generation date
-        var selfDestructTime = Date.now() + (5 * 60 * 1000);
+        var selfDestructDuration = 5 * 60 * 1000;
+
+        var rawParentToken;
+        if (Router.current().route.getName() === "shared") {
```
Comment (zarvox) [inline shell/shared/grain.js]: When the user navigates away from the grain, do we dispose of the `#grain-frame` iframe, or do we simply hide it?  I can see a TOCTOU bug hiding here if the grain frame is hidden, the user navigates elsewhere (changing `Router.current().route`), then the app `postMessage()`s a renderTemplate request.

File: shell/server/hack-session.js [hunk 3]
```diff
@@ -323,10 +323,26 @@ HackSessionContextImpl.prototype.generateApiToken = function (petname, userInfo,
...
+        if (!parentApiToken) {
+          throw new Meteor.Error(403, "No such parent token found.");
+        }
+        userId = parentApiToken.userId;
+        forSharing = parentApiToken.forSharing;
```
Comment (kentonv) [inline shell/server/hack-session.js]: Arguably it makes sense for a child to set `forSharing = true` when the parent had it `false`. This would happen e.g. when Alice creates an API token for use by an app acting on her behalf (forSharing = false), and then the app shares it to another user (forSharing = true).

OTOH, a child token should NOT be able to set forSharing = false when the parent has it true. (Or rather, if it does, this should be ignored.)

Abstractly, the `forSharing` flag on any link disassociates the consumer from any upstream identity.

File: shell/server/hack-session.js [hunk 4]
```diff
@@ -323,10 +323,26 @@ HackSessionContextImpl.prototype.generateApiToken = function (petname, userInfo,
...
+    var userId = this.userId;
+    var parentToken;
+    if (!userId) {
+      if (!rawParentToken) {
+        throw new Meteor.Error(403, "If you are not logged in, you must specify a parent token to " +
+                                    "create a new API token.");
+      } else {
+        check(rawParentToken, String);
+        parentToken = Crypto.createHash("sha256").update(rawParentToken).digest("base64");
+        var parentApiToken = ApiTokens.findOne({_id: parentToken, grainId: grainId,
```
Comment (kentonv) [inline shell/server/hack-session.js]: Mongo injection vulnerability: `grainId` hasn't been validated.

There are a bunch of `check()` calls after this whole new block you added; please move them back to the start of the function.

File: shell/shared/grain.js (hunk 2 above)
Comment (kentonv) [inline shell/shared/grain.js]: We dispose the iframe.

Also, we have this check at the top of the function:

    if (event.origin !== currentAppOrigin) {

So I think that should prevent any app's postMessage() from being interpreted as from some other app.

File: shell/server/hack-session.js (hunk 3 above)
Comment (dwrensha) [inline shell/server/hack-session.js]: If the parent has (forSharing = false) and a user creates a new token using the hypothetical "Asheesh button" (i.e. the "remember token" button) in the webkey menu, then it would make sense for the child to have (forSharing = false). However, maybe that's not an important case now that we have offer templates.

Comment (kentonv) [inline shell/server/hack-session.js]: What I'm saying is that if the parent has (forSharing = false) then the child should have the option of setting it true or false. But if it's true for the parent, then it is necessarily true for the child.

**Comment by dwrensha** [comment]
Comments addressed.
